spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: debug
